/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kineticstudy1;
//import static easyjcckit.QuickPlot.*;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import static java.lang.Math.log;
import static java.lang.Math.log10;
import static java.lang.Math.sqrt;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import java.util.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.*;
import java.awt.print.*;
import java.beans.Statement;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.FilesystemFilter;



/**
 *
 * @author Tukesh
 */
public class Kineticstudy1 extends javax.swing.JFrame {

    public List points = new ArrayList();
    private Object jTextField;
    double tarray[][];
    private int Num_Col;
    int i, rc, cc,Num_Row;
    JTable AUC_Conc_Table;
    JTable AUC_Conc_Table1;
    double x, y, m, z[], w[];
    double x1,y1;
    double a, b, S,ye,yf,cn,pdrc,cum,lpd,inc,cbrtinc,rdc,crrdc,dr,lt,sqt,sumnx= 0.0,sumncum=0.0, xcum=0.0,sumnxcum=0.0,xsqr=0.0,sumnxsqr=0.0,ysqr=0.0;
    double cumysqr=0.0, rzero=0.0, den=0.0, num=0.0,sumnlpd=0.0,lpdsqr=0.0,sumnlpdsqr=0.0,xlpd=0.0,sumnxlpd=0.0,mltsumnxlpd=0.0,den11=0.0,den12=0.0, rfirst=0.0;
    double sqrtx=0.0,sumnsqrtx=0.0,mltsqrtxcum=0.0,sumnmltsqrtxcum=0.0,numhig=0.0,sqrtdenhig=0.0,denhig=0.0,sqrsqrtx=0.0,sumnsqrsqrtx=0.0,rhiguchi=0.0,mltltlpd=0.0,sumnmltltlpd=0.0;
    double sumnlt=0.0,sumnltsumnlpd=0.0,numkpm=0.0,sqrlt=0.0,sumnsqrlt=0.0,denkpm1=0.0,denkpm2=0.0,denkpm=0.0,rkpm=0.0,dif=0.0,xdif=0.0,sumnxdif=0.0;
    double sumndif=0.0,numhc=0.0,mltdif=0.0,sumnmltdif=0.0,denhc1=0.0,sqrrtdenhc1=0.0,rhc=0.0;
    double S2 = 0, xp = 0, yp = 0, S3 = 0, S4 = 0, temp=0.0;
   //*****Variable terms*****
    // x = time,   y = Concentration,   a=slope,    b=intercept,     S=,    ye=y estimate,     yf=Area,        cn=concentration,    lpd=log % drug release,
    //inc=initial concentration,   cbrtinc= cube root of inital drug concentration,    rdc=remaining drug concentration,          crrdc=cube root of remaining drug concentration,
   //dr=drug remaining, lt=log time,   sqt= square rroot of time,    cc=column count ,   rc= row count
    /**
     * Creates new form Kineticstudy
     */
    public Kineticstudy1() {
        initComponents();
        setIcon();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }
    private void setIcon()
    {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("tool icon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Panel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        lblR = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jLabel14 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar3.add(jMenu9);

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 255));
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kineticstudy1/tttt.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Home", jPanel10);

        Panel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name of Drug ");

        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Expt. Done by ");

        jTextField2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date of Experiment ");

        jTextField3.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total no. of Readings ");

        jTextField4.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Volume of Dissolution medium   ");

        jTextField7.setForeground(new java.awt.Color(255, 0, 0));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "litres", "ml"}));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("pH of the Medium");

        jTextField10.setForeground(new java.awt.Color(255, 0, 0));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Save");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("RESET");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton9)
                        .addGap(235, 235, 235)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(557, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(325, Short.MAX_VALUE))
        );

        Panel.addTab("Project details", jPanel2);

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Enter the number of observation");

        jTextField6.setForeground(new java.awt.Color(255, 0, 0));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("CALCULATE LINEAR REGRESSION");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("RESET");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jScrollPane6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane6MouseClicked(evt);
            }
        });
        jScrollPane6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane6KeyPressed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setText("PLOT GRAPH");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Formula    y = mx+c");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Press Enter");

        javax.swing.GroupLayout jScrollPane3Layout = new javax.swing.GroupLayout(jScrollPane3);
        jScrollPane3.setLayout(jScrollPane3Layout);
        jScrollPane3Layout.setHorizontalGroup(
            jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jScrollPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(43, 43, 43)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(jScrollPane3Layout.createSequentialGroup()
                .addGroup(jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jScrollPane3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jScrollPane3Layout.createSequentialGroup()
                        .addGroup(jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jScrollPane3Layout.createSequentialGroup()
                                .addGap(378, 378, 378)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jScrollPane3Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(195, 195, 195)
                        .addGroup(jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jScrollPane3Layout.createSequentialGroup()
                        .addGap(881, 881, 881)
                        .addComponent(jLabel14)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jScrollPane3Layout.setVerticalGroup(
            jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jScrollPane3Layout.createSequentialGroup()
                .addGroup(jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jScrollPane3Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(lblB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(jScrollPane3Layout.createSequentialGroup()
                        .addGroup(jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jScrollPane3Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(165, 165, 165)
                                .addGroup(jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jScrollPane3Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)))
                .addGap(30, 30, 30)
                .addGroup(jScrollPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Panel.addTab("Standard linear graph", jScrollPane3);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Enter the number of observation");

        jTextField5.setForeground(new java.awt.Color(204, 0, 0));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("PLOT GRAPH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("RESET");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("SUBMIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Enter Dilution factor");

        jTextField9.setForeground(new java.awt.Color(204, 0, 0));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Enter initial concentration");

        jTextField11.setForeground(new java.awt.Color(204, 0, 0));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(60, 60, 60))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(60, 60, 60)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(86, 86, 86)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(599, 599, 599))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(297, 297, 297))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.addTab("Test Sample", jPanel3);

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton17.setText("CALCULATE R");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton18.setText("PLOT GRAPH");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(456, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("First Order Model", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton19.setText("CALCULATE R");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton20.setText("PLOT GRAPH");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(jButton20)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Higuchi Model", jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton21.setText("CALCULATE R");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton22.setText("PLOT GRAPH");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButton21)
                .addGap(93, 93, 93)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jButton22)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(472, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Korsmeyer Peppas Model", jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton23.setText("CALCULATE R");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton24.setText("PLOT GRAPH");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton23)
                .addGap(66, 66, 66)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(jButton24)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15))
                .addContainerGap(460, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Hixson Crowell Model", jPanel9);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setForeground(new java.awt.Color(153, 255, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(900, 600));

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.setText("CALCULATE R");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton16.setText("PLOT GRAPH");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(474, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Zero Order Model", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        Panel.addTab("Model identification", jPanel4);

        jTabbedPane1.addTab("Project", Panel);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kineticstudy1/aboutus.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel17)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("About us", jPanel11);

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("Tutorial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kineticstudy1/process.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 697, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Help", jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kineticstudy1/contact us.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 697, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Contact", jPanel13);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 204));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));

        jMenu3.setText("File");
        jMenu3.add(jSeparator1);
        jMenu3.add(jSeparator2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kineticstudy1/printer-icon.png"))); // NOI18N
        jMenuItem5.setText("Print");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kineticstudy1/deletered.png"))); // NOI18N
        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        JFreeChart chart = ChartFactory.createXYLineChart("Zero Order Model", "Time/hrs", "Cumulative % drug release", (XYSeriesCollection) createSampleData3(), PlotOrientation.VERTICAL, false, true, true);
        XYPlot p = chart.getXYPlot();
        p.setRangeGridlinePaint(Color.RED);
        ChartFrame frame = new ChartFrame("line chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        for (i = 0; i < rc - 1; i++)
        {
            sumncum=sumncum+cum;
        }
        //Zero order model
        num=(Num_Row*sumnxcum)-(sumnx*sumncum);
        den=Math.sqrt(((Num_Row*sumnxsqr)-(sumnx*sumnx))*((Num_Row*cumysqr)-(sumncum*sumncum)));
        rzero=num/den;
        jTextField16.setText("R = "+ rzero);
        System.out.print("Rzero = "+rzero);

        System.out.print("num = "+num);

        System.out.print("den = "+den);
        //**Start***
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        JFreeChart chart = ChartFactory.createXYLineChart("Hixson Crowell Model", "Time/hrs", "Drug remain", (XYDataset) createSampleData7(), PlotOrientation.VERTICAL, false, true, true);
        XYPlot p = chart.getXYPlot();
        p.setRangeGridlinePaint(Color.RED);
        ChartFrame frame = new ChartFrame("line chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);

    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        //^^^^^Start**************
        rhc=numhc/sqrrtdenhc1;
        jTextField15.setText("R = "+ rhc);

        //********End**************
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        JFreeChart chart = ChartFactory.createXYLineChart("Korsmeyer Peppas Model", "log Time/hrs", "log % drug release", (XYSeriesCollection) createSampleData6(), PlotOrientation.VERTICAL, false, true, true);
        XYPlot p = chart.getXYPlot();
        p.setRangeGridlinePaint(Color.RED);
        ChartFrame frame = new ChartFrame("line chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);

    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        //*********Start**
        rkpm=numkpm/denkpm;
        jTextField14.setText("R = "+ rkpm);

        //****************End***************
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        JFreeChart chart = ChartFactory.createXYLineChart("Higuchi Model", "√Time", "cumulative % drug release", (XYSeriesCollection) createSampleData5(), PlotOrientation.VERTICAL, false, true, true);
        XYPlot p = chart.getXYPlot();
        p.setRangeGridlinePaint(Color.RED);
        ChartFrame frame = new ChartFrame("line chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        //****Start****

        denhig=((Num_Row*sumnsqrsqrtx)-(sumnsqrtx*sumnsqrtx))*((Num_Row*cumysqr)-(sumncum*sumncum));
        sqrtdenhig=Math.sqrt(denhig);
        rhiguchi= numhig/sqrtdenhig;
        jTextField13.setText("R = "+ rhiguchi);

        //*****End*****
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        JFreeChart chart = ChartFactory.createXYLineChart("First Order Model", "log Time/hrs ", "log % drug release", (XYSeriesCollection) createSampleData4(), PlotOrientation.VERTICAL, false, true, true);
        XYPlot p = chart.getXYPlot();
        p.setRangeGridlinePaint(Color.RED);
        ChartFrame frame = new ChartFrame("line chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        //***Start***

        rfirst=((Num_Row*sumnxlpd)-mltsumnxlpd)/Math.sqrt(den11*den12);
        jTextField12.setText("R = "+ rfirst);

        System.out.println(sumnlpd);
        System.out.println(sumnlpdsqr);
        System.out.println(sumnxlpd);
        System.out.println(mltsumnxlpd);
        System.out.println(den11);
        System.out.println(den12);
        //**End***
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        //--------------------------------------------------
        int rc = AUC_Conc_Table.getRowCount();
        int cc = AUC_Conc_Table.getColumnCount();
        double tarray[][] = new double[rc - 1][16];

        AUC_Conc_Table1 = new JTable(rc, 16);

        JScrollPane JF1 = new JScrollPane(AUC_Conc_Table1);

        String header[] = {"Time", "Area", "Concentration", "% Drug Release","Cumulative Percent Drug Release","Log % drug release", "Cube root of amount of drug remaining", "Log time", "sqrt time", "x*cum", "x2", "y2","lpd2","ltlpd", "lt2", "xdif"};

        for (int i = 0; i < AUC_Conc_Table1.getColumnCount(); i++) {
            TableColumn column1 = AUC_Conc_Table1.getTableHeader().getColumnModel().getColumn(i);

            column1.setHeaderValue(header[i]);
        }

        AUC_Conc_Table1.setSize(750, 550);
        AUC_Conc_Table1.setVisible(true);
        JF1.setVisible(true);
        JF1.setSize(750, 550);
        jScrollPane2.add(JF1);
        jScrollPane2.setSize(750, 550);
        jScrollPane2.setVisible(true);

        cum = 0.0;
        cbrtinc = Math.cbrt(inc);
        for (i = 0; i < rc - 1; i++) {
            tarray[i][0] = Double.parseDouble(AUC_Conc_Table.getValueAt(i, 0).toString());
            x = tarray[i][0];
            tarray[i][1] = Double.parseDouble(AUC_Conc_Table.getValueAt(i, 1).toString());
            y = tarray[i][1];

            //TTTT

            yf = (y - a)/ b;
            jLabel14.setText(((10000 / 10000) * yf) + "");

            //Dilution Factor
            double df = Integer.parseInt(jTextField9.getText());
            cn=yf*df;
            inc = Integer.parseInt(jTextField11.getText());
            pdrc = (cn/inc)*100;

            //Cumulative % Drug release calculation
            cum = pdrc+cum;
            //end
            //Log % drug release
            lpd=Math.log(pdrc)/Math.log(10);
            //cube root of drug percentage remaining
            rdc=inc-cn;
            crrdc= Math.cbrt(rdc);
            dr=cbrtinc-crrdc;
            //Log of time
            lt=log10(x);
            sqrlt=lt*lt;
            sumnsqrlt=sumnsqrlt+sqrlt;
            sumnlt=sumnlt+lt;
            //square root of time
            sqt=sqrt(x);

            sumnx=sumnx+x;
            sumncum=sumncum+cum;

            xcum=x*cum;
            sumnxcum=sumnxcum+xcum;
            xsqr=x*x;

            sumnxsqr=sumnxsqr+xsqr;

            ysqr=cum*cum;

            cumysqr=cumysqr+ysqr;

            sumnlpd=sumnlpd+lpd;

            lpdsqr=lpd*lpd;
            sumnlpdsqr=sumnlpdsqr+lpdsqr;
            xlpd=x*lpd;
            sumnxlpd=sumnxlpd+xlpd;
            mltsumnxlpd=sumnx*sumnlpd;
            // denominator of first order first part (den11)and second part (den12)
            den11=((Num_Row*sumnxsqr)-(sumnx*sumnx));
            den12=(Num_Row*sumnlpdsqr)-(sumnlpd*sumnlpd);
            //************
            //********************************************************************************Higuchi
            //square root of time
            sqrtx=Math.sqrt(x);
            mltsqrtxcum=sqrtx*cum;
            //
            sumnmltsqrtxcum=sumnmltsqrtxcum+mltsqrtxcum;
            sumnsqrtx= sumnsqrtx+sqrtx;
            numhig=(Num_Row*sumnmltsqrtxcum)-(sumnsqrtx*sumncum);
            sqrsqrtx=sqrtx*sqrtx;
            sumnsqrsqrtx=sumnsqrsqrtx+sqrsqrtx;
            //*****************************************************************Korsmeyer Peppas Model
            //Numerator
            mltltlpd=lt*lpd;
            sumnmltltlpd=sumnmltltlpd+mltltlpd;
            sumnltsumnlpd=sumnlt*sumnlpd;
            numkpm=(Num_Row*sumnmltltlpd)-sumnltsumnlpd;
            //Denominator
            denkpm1=(Num_Row*sumnsqrlt)-(sumnlt*sumnlt);
            denkpm2=(Num_Row*sumnlpdsqr)-(sumnlpd*sumnlpd);
            denkpm=Math.sqrt(denkpm1*denkpm2);

            //********************************************************************HixsonCrowell Model

            dif= cbrtinc-crrdc;
            sumndif=sumndif+dif;
            xdif=x*dif;
            sumnxdif=sumnxdif+xdif;
            //Numerator
            numhc=(Num_Row*sumnxdif)-(sumnx*sumndif);
            //Denominator
            mltdif=dif*dif;
            sumnmltdif=sumnmltdif+mltdif;
            denhc1=((Num_Row*sumnxsqr)-(sumnx*sumnx))*(Num_Row*sumnmltdif)-(sumndif*sumndif);
            sqrrtdenhc1=Math.sqrt(denhc1);

            AUC_Conc_Table1.setValueAt(AUC_Conc_Table.getValueAt(i, 0).toString(), i, 0);
            AUC_Conc_Table1.setValueAt(AUC_Conc_Table.getValueAt(i, 1).toString(), i, 1);
            AUC_Conc_Table1.setValueAt(cn, i, 2);
            AUC_Conc_Table1.setValueAt(pdrc, i, 3);
            AUC_Conc_Table1.setValueAt(cum, i, 4);
            AUC_Conc_Table1.setValueAt(lpd, i, 5);
            AUC_Conc_Table1.setValueAt(dr, i, 6);
            AUC_Conc_Table1.setValueAt(lt, i, 7);
            AUC_Conc_Table1.setValueAt(sqt, i, 8);
            AUC_Conc_Table1.setValueAt(xcum, i, 9);
            AUC_Conc_Table1.setValueAt(xsqr, i, 10);
            AUC_Conc_Table1.setValueAt(ysqr, i, 11);
            AUC_Conc_Table1.setValueAt(lpdsqr, i, 12);
            AUC_Conc_Table1.setValueAt(mltltlpd, i, 13);
            AUC_Conc_Table1.setValueAt(sqrlt, i, 14);
            AUC_Conc_Table1.setValueAt(xdif, i, 15);

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextField5.setText(null);
        jTextField11.setText(null);
        jTextField9.setText(null);
        jScrollPane5.removeAll();
        jScrollPane2.removeAll();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //******GRAPH*******

        JFreeChart chart = ChartFactory.createXYLineChart("  Linear Regression  ", " Time  ", "  Concentration  ", (XYSeriesCollection) createSampleData2(), PlotOrientation.VERTICAL, false, true, true);
        XYPlot p = chart.getXYPlot();
        p.setRangeGridlinePaint(Color.RED);
        ChartFrame frame = new ChartFrame("line chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);

        //*****END********
        System.out.println(x);
        System.out.println(y);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int Num_Row = Integer.parseInt(jTextField5.getText());

        AUC_Conc_Table = new JTable(Num_Row + 1, 2);

        JScrollPane JF = new JScrollPane(AUC_Conc_Table);
        String header[] = {"Time", "Area"};

        for (int i = 0; i < AUC_Conc_Table.getColumnCount(); i++) {
            TableColumn column1 = AUC_Conc_Table.getTableHeader().getColumnModel().getColumn(i);

            column1.setHeaderValue(header[i]);
        }
        AUC_Conc_Table.setSize(250, 150);
        AUC_Conc_Table.setVisible(true);
        JF.setVisible(true);
        JF.setSize(250, 150);
        jScrollPane5.add(JF);
        //**

        jScrollPane5.setSize(250, 150);
        jScrollPane5.setVisible(true);

        AUC_Conc_Table.setValueAt("Press Enter", Num_Row, 0);
        AUC_Conc_Table.setValueAt("--", Num_Row, 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField10.setText(null);
        jTextField7.setText(null);
        jComboBox3.removeAll();
        //lblE.setText(null);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //************Start*************
        
        JFileChooser fs = new JFileChooser();
        fs.setDialogTitle("Save file as");
        fs.setFileFilter(new FilesystemFilter (".pdf", "PDF File"));
        fs.setFileFilter(new FilesystemFilter (".doc", "DOC File"));
        fs.setFileFilter(new FilesystemFilter (".txt", "TXT File"));
        int result = fs.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION)
        {
         String Drug_Name = String.valueOf(jTextField1.getText());
        String Expdby = String.valueOf(jTextField2.getText());
        String Doe = String.valueOf(jTextField3.getText());
        String Tnoread = String.valueOf(jTextField4.getText());
        String ph = String.valueOf(jTextField10.getText());
        String volm = String.valueOf(jTextField7.getText());
        String unit = String.valueOf(jComboBox3.getSelectedItem());
            
        
        File fi = fs.getSelectedFile();
        
//        //
//        Document doc = new Document();
        try {
            
            PrintWriter fw = new PrintWriter(fi.getPath());
            fw.println("Name of the Drug : " +Drug_Name);
            fw.println("Experiment Done by : "+Expdby);
            fw.println("Date of experiment : " +Doe);
            fw.println("Total no of readings : " +Tnoread);
            fw.println("pH of the medium : " +ph);
            fw.println("Volume of medium : " +volm +" "+unit);
            
            
            fw.flush();
            fw.close();
            
//            PdfWriter.getInstance(doc, new FileOutputStream("Kinetic_model.pdf"));
//            doc.open();
//            fw.write(new Paragraph("Name of the Drug : " +Drug_Name));
//            doc.add(new Paragraph("Experiment Done by : " +Expdby));
//            doc.add(new Paragraph("Date of experiment : " +Doe));
//            doc.add(new Paragraph("Total no of readings : " +Tnoread));
//            doc.add(new Paragraph("pH of the medium : " +ph));
//            doc.add(new Paragraph("Volume of medium : " +volm +" "+unit));
//            doc.close();
            //Num_Row = Integer.parseInt(jTextField6.getText());
       }
//            catch (FileNotFoundException | DocumentException ex) {
//            Logger.getLogger(Kineticstudy1.class.getName()).log(Level.SEVERE, null, ex);
//        }
      catch (Exception e2) 
      {
      JOptionPane.showMessageDialog(null, e2.getMessage());
      }
          }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        WindowEvent winClosingEvent = new  WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        MessageFormat header = new MessageFormat("Standard and Test Table ");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try {
            AUC_Conc_Table.print(JTable.PrintMode.NORMAL, header, footer);
            AUC_Conc_Table1.print(JTable.PrintMode.NORMAL, header, footer);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try 
        {
        Desktop.getDesktop().open(new File(".\\lib\\tool manual.pdf"));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:

        JFreeChart chart = ChartFactory.createXYLineChart("  Linear Regression  ", " Concentration  ", " Area ", (XYDataset) createSampleData(), PlotOrientation.VERTICAL, false, true, true);
        XYPlot p = chart.getXYPlot();
        p.setRangeGridlinePaint(Color.RED);
        ChartFrame frame = new ChartFrame("line chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jScrollPane6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane6KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int N;
            N = Integer.parseInt(jTextField6.getText());
            double S = 0, x, y;

            for (int i = 0; i < N; i++) {
                S = S + Double.parseDouble(AUC_Conc_Table.getValueAt(i, 0).toString());
                S2 = S2 + Double.parseDouble(AUC_Conc_Table.getValueAt(i, 1).toString());
            }
            xp = S / N;
            yp = S2 / N;
            for (int i = 0; i < N; i++) {
                x = Double.parseDouble(AUC_Conc_Table.getValueAt(i, 0).toString());
                y = Double.parseDouble(AUC_Conc_Table.getValueAt(i, 1).toString());
                S3 = S3 + (x - xp) * (y - yp);
                S4 = S4 + (x - xp) * (x - xp);

            }
            b = S3 / S4;
            a = yp - b * xp;
            a = Math.rint(a * 10000) / 10000;
            // System.out.println(Math.rint(a*10000));
            b = Math.rint(b * 10000) / 10000;
            lblR.setText("a=" + a);
            lblB.setText("b=" + b);
            lblE.setText("y=" + a + "+" + b + "x");

        }
    }//GEN-LAST:event_jScrollPane6KeyPressed

    private void jScrollPane6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane6MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jTextField6.setText(null);
       // jTextField8.setText(null);
        jScrollPane6.removeAll();
        lblE.setText(null);
        lblR.setText(null);
        lblB.setText(null);
        //jLabel14.setText(null);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int N;
        N = Integer.parseInt(jTextField6.getText());
        double S = 0, x, y;

        for (int i = 0; i < N; i++) {
            S = S + Double.parseDouble(AUC_Conc_Table.getValueAt(i, 0).toString());
            S2 = S2 + Double.parseDouble(AUC_Conc_Table.getValueAt(i, 1).toString());
        }
        xp = S / N;
        yp = S2 / N;
        for (int i = 0; i < N; i++) {
            x = Double.parseDouble(AUC_Conc_Table.getValueAt(i, 0).toString());
            y = Double.parseDouble(AUC_Conc_Table.getValueAt(i, 1).toString());
            S3 = S3 + (x - xp) * (y - yp);
            S4 = S4 + (x - xp) * (x - xp);

        }
        b = S3 / S4;
        a = yp - b * xp;
        a = Math.rint(a * 10000) / 10000;
        // System.out.println(Math.rint(a*10000));
        b = Math.rint(b * 10000) / 10000;
        lblR.setText("a=" + a);
        lblB.setText("b=" + b);
        lblE.setText("y=" + a + "+" + b + "x");

        //        try
        //        {
            //        String fileName = "E:\\file.xls";
            //        WritableWorkbook workbook = Workbook.createWorkbook(new File(fileName));.
            //        WritableSheet sheet = workbook.createSheet("sheet1",0);
            //        }
        //        catch()
        //        {
            //        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Num_Row = Integer.parseInt(jTextField6.getText());

            AUC_Conc_Table = new JTable(Num_Row + 1, 2);

            String header[] = {"Concentration (x)", "Area (y)"};

            for (int i = 0; i < AUC_Conc_Table.getColumnCount(); i++) {
                TableColumn column1 = AUC_Conc_Table.getTableHeader().getColumnModel().getColumn(i);

                column1.setHeaderValue(header[i]);
            }
            AUC_Conc_Table.setSize(250, 150);
            AUC_Conc_Table.setVisible(true);
            AUC_Conc_Table.setValueAt("Press Enter", Num_Row, 0);
            AUC_Conc_Table.setValueAt("--", Num_Row, 1);

            //            JScrollPane JF = new JScrollPane(AUC_Conc_Table);
            //            JF.setVisible(true);
            //            JF.setSize(250, 150);
            JScrollPane JF = new JScrollPane(AUC_Conc_Table);
            JF.setVisible(true);
            JF.setSize(250, 150);

            jScrollPane6.add(JF);
            //**
            JF.grabFocus();
            JF.repaint();
            //   jScrollPane6.addMouseListener();

            jScrollPane6.setSize(250, 150);
            jScrollPane6.setVisible(true);
            //   jScrollPane6.repaint();
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
    private XYDataset createSampleData()
        {
        XYSeriesCollection dataset = new XYSeriesCollection();
        double xy[][] = new double[AUC_Conc_Table.getRowCount() - 1][2];
        XYSeries series1 = new XYSeries("MyData");
        for (i = 0; i < AUC_Conc_Table.getRowCount() - 1; i++) {
            x = Double.parseDouble(AUC_Conc_Table.getValueAt(i, 1).toString());
            y = Double.parseDouble(AUC_Conc_Table.getValueAt(i, 0).toString());
            xy[i][0] = x;
            xy[i][1] = y;
            series1.add(x, y);
          
        }
        dataset.addSeries(series1);
        return dataset;
         ////***********
      
        }
    //**************************************************************************Zero Order*********************************Start***********
   private XYSeriesCollection createSampleData3()
        {
        XYSeriesCollection dataset = new XYSeriesCollection();
        double xy[][] = new double[AUC_Conc_Table1.getRowCount() - 1][2];
        XYSeries series1 = new XYSeries("MyData");
        for (i = 0; i < AUC_Conc_Table1.getRowCount() - 1; i++) {
            x = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 4).toString());
            y = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 0).toString());
            xy[i][0] = x;
            xy[i][1] = y;
            series1.add(x, y);
          
        }
        dataset.addSeries(series1);
        return dataset;
        //**********************************************************End**************************************************
         ////***********
      
        }
   //*********************************************************First order Model**************************Start*************************
    private XYSeriesCollection createSampleData4()
        {
        XYSeriesCollection dataset = new XYSeriesCollection();
        double xy[][] = new double[AUC_Conc_Table1.getRowCount() - 1][2];
        XYSeries series1 = new XYSeries("MyData");
        for (i = 0; i < AUC_Conc_Table1.getRowCount() - 1; i++) {
            x = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 5).toString());
            y = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 0).toString());
            xy[i][0] = x;
            xy[i][1] = y;
            series1.add(x, y);
          
        }
        dataset.addSeries(series1);
        return dataset;
        
         ////***********
         }
    //**********************************************************End**************************************************
    
    //*********************************************************Higuchi Model**************************Start*************************
    private XYSeriesCollection createSampleData5()
        {
        XYSeriesCollection dataset = new XYSeriesCollection();
        double xy[][] = new double[AUC_Conc_Table1.getRowCount() - 1][2];
        XYSeries series1 = new XYSeries("MyData");
        for (i = 0; i < AUC_Conc_Table1.getRowCount() - 1; i++) {
            x = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 4).toString());
            y = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 8).toString());
            xy[i][0] = x;
            xy[i][1] = y;
            series1.add(x, y);
          
        }
        dataset.addSeries(series1);
        return dataset;
        
         ////***********
         }
    //**********************************************************End**************************************************
    
   // ***************************************************Korsmeyer Peppas Model**********************Start********************
    private XYSeriesCollection createSampleData6()
        {
        XYSeriesCollection dataset = new XYSeriesCollection();
        double xy[][] = new double[AUC_Conc_Table1.getRowCount() - 1][2];
        XYSeries series1 = new XYSeries("MyData");
        for (i = 0; i < AUC_Conc_Table1.getRowCount() - 1; i++) {
            x = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 5).toString());
            y = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 7).toString());
            xy[i][0] = x;
            xy[i][1] = y;
            series1.add(x, y);
          
        }
        dataset.addSeries(series1);
        return dataset;
        
         ////***********
         }
    //**********************************************************End**************************************************
   
    // ***************************************************Hixson Crowell Model**********************Start********************
    private XYSeriesCollection createSampleData7()
        {
        XYSeriesCollection dataset = new XYSeriesCollection();
        double xy[][] = new double[AUC_Conc_Table1.getRowCount() - 1][2];
        XYSeries series1 = new XYSeries("MyData");
        for (i = 0; i < AUC_Conc_Table1.getRowCount() - 1; i++) {
            x = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 6).toString());
            y = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 0).toString());
            xy[i][0] = x;
            xy[i][1] = y;
            series1.add(x, y);
          
        }
        dataset.addSeries(series1);
        return dataset;
        
         ////***********
         }
    //**********************************************************End**************************************************
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kineticstudy1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kineticstudy1().setVisible(true);
            }
        });
    }
    private XYSeriesCollection createSampleData2()
    {
          XYSeriesCollection dataset = new XYSeriesCollection();
        double xy[][] = new double[AUC_Conc_Table1.getRowCount() - 1][2];
        XYSeries series1 = new XYSeries("MyData");
        for (i = 0; i < AUC_Conc_Table1.getRowCount() - 1; i++) {
            x = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 4).toString());
            y = Double.parseDouble(AUC_Conc_Table1.getValueAt(i, 2).toString());
            xy[i][0] = x;
            xy[i][1] = y;
            series1.add(x, y);
          
        }
        dataset.addSeries(series1);
        return dataset;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblR;
    // End of variables declaration//GEN-END:variables

    private void getComponents(JTable Auc_Time_Table) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class Userino_frame {

        public Userino_frame() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
